version: '3'

services:
  mongo:
    image: "mongo:3"
    ports:
    - 27747:27017
    networks:
    - lto

  api-gateway:
    container_name: api-gateway
    image: legalthings/api-gateway:v0.1.4
    environment:
    - NODE_ENV=production
    ports:
    - "3000:80"
    networks:
    - lto

  legalflow:
    container_name: legalflow
    image: legalthings/workflow-engine:v0.1.2
    environment:
    - APPLICATION_ENV=dev.docker
    - phpmemory_limit=512M
    networks:
    - lto
    depends_on:
    - mongo

  legalevents:
    container_name: legalevents
    image: legalthings/event-chain:v0.1.1
    environment:
    - APPLICATION_ENV=dev.docker
    - phpmemory_limit=512M
    networks:
    - lto
    depends_on:
    - mongo

networks:
  lto:
    driver: bridge
